version: '3.4'

services:
  alpine-nginx-with-theia-web-ide-hobo:
    image: hackinglab/alpine-nginx-with-theia-web-ide:latest
    hostname: 'hobo'
    user: root
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:e0.idocker.hacking-lab.com"
      - "traefik.protocol=http"
